// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Complex.proto

package ru.itmo.java.message.complex;

public interface BaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.complex.BaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.complex.EchoRequest echoRequest = 1;</code>
   * @return Whether the echoRequest field is set.
   */
  boolean hasEchoRequest();
  /**
   * <code>.ru.itmo.java.message.complex.EchoRequest echoRequest = 1;</code>
   * @return The echoRequest.
   */
  ru.itmo.java.message.complex.EchoRequest getEchoRequest();
  /**
   * <code>.ru.itmo.java.message.complex.EchoRequest echoRequest = 1;</code>
   */
  ru.itmo.java.message.complex.EchoRequestOrBuilder getEchoRequestOrBuilder();

  /**
   * <code>.ru.itmo.java.message.complex.CalculationRequest calculationRequest = 2;</code>
   * @return Whether the calculationRequest field is set.
   */
  boolean hasCalculationRequest();
  /**
   * <code>.ru.itmo.java.message.complex.CalculationRequest calculationRequest = 2;</code>
   * @return The calculationRequest.
   */
  ru.itmo.java.message.complex.CalculationRequest getCalculationRequest();
  /**
   * <code>.ru.itmo.java.message.complex.CalculationRequest calculationRequest = 2;</code>
   */
  ru.itmo.java.message.complex.CalculationRequestOrBuilder getCalculationRequestOrBuilder();

  public ru.itmo.java.message.complex.BaseRequest.RequestCase getRequestCase();
}
