// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Complex.proto

package ru.itmo.java.message.complex;

public interface BaseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.complex.BaseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.complex.EchoResponse echoResponse = 1;</code>
   * @return Whether the echoResponse field is set.
   */
  boolean hasEchoResponse();
  /**
   * <code>.ru.itmo.java.message.complex.EchoResponse echoResponse = 1;</code>
   * @return The echoResponse.
   */
  ru.itmo.java.message.complex.EchoResponse getEchoResponse();
  /**
   * <code>.ru.itmo.java.message.complex.EchoResponse echoResponse = 1;</code>
   */
  ru.itmo.java.message.complex.EchoResponseOrBuilder getEchoResponseOrBuilder();

  /**
   * <code>.ru.itmo.java.message.complex.CalculationResponse calculationResponse = 2;</code>
   * @return Whether the calculationResponse field is set.
   */
  boolean hasCalculationResponse();
  /**
   * <code>.ru.itmo.java.message.complex.CalculationResponse calculationResponse = 2;</code>
   * @return The calculationResponse.
   */
  ru.itmo.java.message.complex.CalculationResponse getCalculationResponse();
  /**
   * <code>.ru.itmo.java.message.complex.CalculationResponse calculationResponse = 2;</code>
   */
  ru.itmo.java.message.complex.CalculationResponseOrBuilder getCalculationResponseOrBuilder();

  public ru.itmo.java.message.complex.BaseResponse.ResponseCase getResponseCase();
}
