// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Complex.proto

package ru.itmo.java.message.complex;

public interface CalculationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.complex.CalculationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();
}
