// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Complex.proto

package ru.itmo.java.message.complex;

public interface CalculationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.complex.CalculationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>.ru.itmo.java.message.complex.CalculationRequest.Operation operation = 3;</code>
   * @return The enum numeric value on the wire for operation.
   */
  int getOperationValue();
  /**
   * <code>.ru.itmo.java.message.complex.CalculationRequest.Operation operation = 3;</code>
   * @return The operation.
   */
  ru.itmo.java.message.complex.CalculationRequest.Operation getOperation();
}
