// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Array.proto

package ru.itmo.java.message.simple;

public interface MyArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.simple.MyArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 array = 1;</code>
   * @return A list containing the array.
   */
  java.util.List<java.lang.Integer> getArrayList();
  /**
   * <code>repeated int32 array = 1;</code>
   * @return The count of array.
   */
  int getArrayCount();
  /**
   * <code>repeated int32 array = 1;</code>
   * @param index The index of the element to return.
   * @return The array at the given index.
   */
  int getArray(int index);
}
