// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package ru.itmo.java.message.simple;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.simple.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
