// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package ru.itmo.java.message.simple;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.simple.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.simple.Person person = 1;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>.ru.itmo.java.message.simple.Person person = 1;</code>
   * @return The person.
   */
  ru.itmo.java.message.simple.Person getPerson();
  /**
   * <code>.ru.itmo.java.message.simple.Person person = 1;</code>
   */
  ru.itmo.java.message.simple.PersonOrBuilder getPersonOrBuilder();
}
